"""
Django settings for consultoriodigital project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from utils.database_selector import get_local_database_name
from django.conf import settings



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4%_k=9o!mb9@cq@8i3+jbrfx5@h#vgj1y21isb=r09bdu2zog0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # *******************************************************


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cdigital', #aplicação que eu criei # ****************************************
    'bootstrap4', # **************************************************************
    'stdimage',   # ************************************************************** 
    'widget_tweaks',#************************************************************* 
    'crispy_forms',         
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # <-- TEM QUE VIR AQUI
    'cdigital.middleware.ClienteDBMiddleware',               # <-- DEPOIS da sessão
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'consultoriodigital.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], # **************************************************************
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TUSS_XLSX_PATH = r'C:\Cdigital\codigos.xlsx'

WSGI_APPLICATION = 'consultoriodigital.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ************************************************************** USANDO MYSQL


#cliente_db = get_local_database_name()
import configparser

config = configparser.ConfigParser()
config.read('C:\\cdigital\\bd.ini')
cliente_db_name = config.get('database', 'nome', fallback=None)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':cliente_db_name,
        'USER':'Usuario_Root',
        'PASSWORD':'Tr18365518AaBbCcDdEe#!',
        'HOST':'localhost',
        'PORT':'3308',
    },

    'cliente_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': cliente_db_name,
        'USER': 'Usuario_Root',
        'PASSWORD': 'Tr18365518AaBbCcDdEe#!',
        'HOST': 'localhost',
        'PORT': '3308',
    }
}

DATABASE_ROUTERS = ['cdigital.db_router.MultiTenantRouter']
#DATABASE_ROUTERS = ['cdigital.db_router.DatabaseRouter']

# **************************************************************
# ************************************************************** USANDO POSTGRESQL COM HEROKU
#DATABASES = {
#        'default': dj_database_url.config(default='sqlite:///db.sqlite3', 
#        conn_max_age=600)
#}    

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' # **************************************************************

TIME_ZONE = 'America/Sao_Paulo' # ******************************************************

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For production static files # 
# Durante o desenvolvimento:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

#************************************************************************************

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://3df7d7555a8d.ngrok-free.app',
]

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True