# Generated by Django 5.2.4 on 2025-07-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
