# Generated by Django 5.2.4 on 2025-07-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='valor_repasse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
