# Generated by Django 5.2.4 on 2025-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0002_alter_clientes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
