# Generated by Django 5.2.4 on 2025-07-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0002_convenios_valor_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentos',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
