# Generated by Django 5.2.4 on 2025-07-19 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0003_atendimentos_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='conta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdigital.banco'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Código deve conter apenas números', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='receita',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Código deve conter apenas números', regex='^\\d+$')]),
        ),
    ]
