# Generated by Django 5.2.4 on 2025-07-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0004_contapagar_conta_origem_alter_despesa_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidasmonetarias',
            name='conta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdigital.banco'),
        ),
    ]
