# Generated by Django 5.2.4 on 2025-07-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0004_agenda_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='modigicado',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Login'),
        ),
    ]
