# Generated by Django 5.2.4 on 2025-07-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0005_remove_usuarios_ativo_remove_usuarios_criado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='profissional',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='cdigital.usuarios'),
            preserve_default=False,
        ),
    ]
