# Generated by Django 5.2.4 on 2025-07-19 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0005_saidasmonetarias_conta_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='recebido',
        ),
        migrations.AddField(
            model_name='contareceber',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdigital.banco'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdigital.receita'),
        ),
    ]
