# Generated by Django 5.2.4 on 2025-07-09 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0006_agenda_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='modigicado',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='criado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdigital.usuarios'),
        ),
    ]
