# Generated by Django 5.2.4 on 2025-07-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0006_remove_contareceber_convenio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasmonetarias',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdigital.banco'),
        ),
    ]
