# Generated by Django 5.2.4 on 2025-07-11 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0007_remove_agenda_ativo_remove_agenda_modigicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentos',
            name='profissional',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='cdigital.usuarios'),
            preserve_default=False,
        ),
    ]
