# Generated by Django 5.2.4 on 2025-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0007_entradasmonetarias_conta_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
