# Generated by Django 5.2.4 on 2025-07-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0008_agenda_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='carteirinha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdigital.convenios'),
        ),
    ]
