# Generated by Django 5.2.4 on 2025-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0008_atendimentos_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_medico',
            field=models.BooleanField(default=False),
        ),
    ]
