# Generated by Django 5.2.4 on 2025-07-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0009_clientes_carteirinha_clientes_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM'),
        ),
    ]
