# Generated by Django 5.2.4 on 2025-07-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0010_convenios_alter_usuarios_is_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='nomeconvenio',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
