# Generated by Django 5.2.4 on 2025-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0011_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenios',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='convenios',
            name='registro_ans',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
