# Generated by Django 5.2.4 on 2025-07-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0011_alter_convenios_nomeconvenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdigital.convenios'),
        ),
    ]
