# Generated by Django 5.2.4 on 2025-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0012_convenios_cnpj_convenios_registro_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='registro_ans',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
