# Generated by Django 5.2.4 on 2025-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0012_agenda_convenio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='convenios',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='convenios',
            name='modigicado',
        ),
        migrations.AddField(
            model_name='convenios',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
