# Generated by Django 5.2.4 on 2025-07-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0013_empresa_registro_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Outro'), ('4', 'Prefiro não informar')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
