# Generated by Django 5.2.4 on 2025-07-14 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0013_remove_convenios_ativo_remove_convenios_criado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenios',
            name='valor_pago',
        ),
        migrations.AddField(
            model_name='convenios',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='convenios',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convenios',
            name='modigicado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
    ]
