# Generated by Django 5.2.4 on 2025-07-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0014_clientes_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentos',
            name='codigo_tuss',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código TUSS'),
        ),
        migrations.AddField(
            model_name='atendimentos',
            name='descricao_tuss',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição TUSS'),
        ),
    ]
