# Generated by Django 5.2.4 on 2025-07-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0015_atendimentos_codigo_tuss_atendimentos_descricao_tuss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
