# Generated by Django 5.2.4 on 2025-07-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0016_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentos',
            name='codigo_tuss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigo_atendimentos', to='cdigital.servico'),
        ),
        migrations.AlterField(
            model_name='atendimentos',
            name='descricao_tuss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descricao_atendimentos', to='cdigital.servico'),
        ),
    ]
