# Generated by Django 5.2.4 on 2025-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0017_alter_atendimentos_codigo_tuss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='codigo_servico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='descricao_servico',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='entradasmonetarias',
            name='codigo_servico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entradasmonetarias',
            name='descricao_servico',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
