# Generated by Django 5.2.4 on 2025-08-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdigital', '0019_alter_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='favorecido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='favorecido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entradasmonetarias',
            name='favorecido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saidasmonetarias',
            name='favorecido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
